import java.util.Scanner;

public class Proiblem_2 {
    public static void main(String[] args) {
//Even Fibonacci numbers
      /*
        Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
       */
        Scanner sc = new Scanner(System.in);
        int n1 = 0;
        int n2 = 1;
        int i = sc.nextInt();
        while (i-- != 0) {
            int c = n1 + n2;
            System.out.print(c + ", ");
            n1 = n2;
            n2 = c;
        }
        System.out.println(" ...");
    }
}
